laravel/app/Http/routes.php
<?php

Route::group(['middleware' => ['web']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('quem-somos', 'QuemSomosController@index')->name('quem-somos');
    Route::get('atuacao', 'AtuacaoController@index')->name('atuacao');
    Route::get('noticias-e-publicacoes', 'NoticiasController@index')->name('noticias');
    Route::get('noticias-e-publicacoes/{noticia_slug}', 'NoticiasController@show')->name('noticias.show');
    Route::get('blog/{blog_categoria_slug?}', 'BlogController@index')->name('blog');
    Route::get('blog/{blog_categoria_slug}/{blog_slug}', 'BlogController@show')->name('blog.show');
    Route::post('blog-comentario', 'BlogController@comentario');
    Route::get('contato', 'ContatoController@index')->name('contato');
    Route::post('contato', 'ContatoController@post')->name('contato.post');

    // Painel
    Route::group([
        'prefix'     => 'painel',
        'namespace'  => 'Painel',
        'middleware' => ['auth']
    ], function() {
        Route::get('/', 'PainelController@index')->name('painel');

        /* GENERATED ROUTES */
		Route::resource('blog/cabecalho', 'BlogCabecalhoController', ['only' => ['index', 'update']]);
		Route::resource('blog/categorias', 'BlogCategoriasController');
        Route::resource('blog', 'BlogPostsController');
        Route::get('blog/{blog}/comentarios/{comentarios}/aprovacao', 'BlogComentariosController@aprovacao')->name('painel.blog.comentarios.aprovacao');
        Route::resource('blog.comentarios', 'BlogComentariosController');
		Route::resource('noticias/cabecalho', 'NoticiasCabecalhoController', ['only' => ['index', 'update']]);
		Route::resource('noticias', 'NoticiasController');
		Route::resource('atuacao', 'AtuacaoController', ['only' => ['index', 'update']]);
		Route::resource('profissionais', 'ProfissionaisController');
		Route::resource('quem-somos', 'QuemSomosController', ['only' => ['index', 'update']]);
		Route::resource('home', 'HomeController', ['only' => ['index', 'update']]);
        Route::resource('contato/recebidos', 'ContatosRecebidosController');
        Route::resource('contato', 'ContatoController');
        Route::resource('usuarios', 'UsuariosController');

        Route::post('ckeditor-upload', 'PainelController@imageUpload');
        Route::post('order', 'PainelController@order');
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
    });

    // Auth
    Route::group([
        'prefix'    => 'painel',
        'namespace' => 'Auth'
    ], function() {
        Route::get('login', 'AuthController@showLoginForm')->name('auth');
        Route::post('login', 'AuthController@login')->name('login');
        Route::get('logout', 'AuthController@logout')->name('logout');
    });
});

laravel/app/Models/ContatoRecebido.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class ContatoRecebido extends Model
{
    protected $table = 'contatos_recebidos';

    protected $guarded = ['id'];

    public function getCreatedAtAttribute($date)
    {
        return \Carbon\Carbon::createFromFormat('Y-m-d H:i:s', $date)->format('d/m/Y');
    }

    public function scopeNaoLidos($query)
    {
        return $query->where('lido', '!=', 1);
    }

    public function countNaoLidos()
    {
        return $this->naoLidos()->count();
    }
}

laravel/app/Http/Controllers/BlogController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Requests\BlogComentariosRequest;

use App\Models\BlogCategoria;
use App\Models\BlogPost;
use App\Models\BlogCabecalho;

class BlogController extends Controller
{
    public function index(BlogCategoria $categoria, Request $request)
    {
        $posts = (! $categoria->exists)
            ? BlogPost::ordenados()
            : BlogPost::ordenados()->categoria($categoria->id);

        if ($request->ajax()) {
            return response()->json([
                'list'       => $posts->with('categoria')->paginate(10),
                'thumbs'     => $posts->paginate(3, ['id'], 'page_thumbs'),
                'thumbsHtml' => view('frontend.blog.thumbs', [
                    'posts' => $posts->paginate(3, ['*'], 'page_thumbs')
                ])->render()
            ]);
        }

        $categorias    = BlogCategoria::ordenados()->select('slug', 'titulo')->get();
        $postsList     = $posts->paginate(10);
        $postsThumbs   = $posts->paginate(3, ['*'], 'page_thumbs');
        $blogCabecalho = BlogCabecalho::first();

        return view('frontend.blog.index', compact('categorias', 'postsList', 'postsThumbs', 'blogCabecalho', 'categoria'));
    }

    public function show(BlogCategoria $categoria, BlogPost $post)
    {
        $posts = (! $categoria->exists)
            ? BlogPost::ordenados()
            : BlogPost::ordenados()->categoria($categoria->id);

        $categorias    = BlogCategoria::ordenados()->select('slug', 'titulo')->get();
        $postsList     = $posts->paginate(10);
        $blogCabecalho = BlogCabecalho::first();

        return view('frontend.blog.show', compact('categorias', 'postsList', 'post', 'blogCabecalho'));
    }

    public function comentario(BlogComentariosRequest $request)
    {
        try {

            $post = BlogPost::findOrFail($request->get('post'));
            $post->comentarios()->create($request->except('post'));

            \Mail::send('emails.comentario', [
                'comentario' => $request->all(),
                'post'       => $post
            ], function($message) use ($request) {
                $message->to('blog@vmradvocacia.com.br', 'Vieira de Mello Rudge Advocacia')
                        ->subject('[NOVO COMENTÁRIO] Vieira de Mello Rudge Advocacia');
            });

        } catch (\Exception $e) {

            $response = [
                'message' => 'Ocorreu um erro. Tente novamente.'
            ];
            return response()->json($response);

        }

        $response = [
            'success' => true,
            'message' => 'Comentário enviado com sucesso. Sujeito à aprovação da moderação.'
        ];
        return response()->json($response);
    }
}

laravel/resources/views/frontend/blog/index.blade.php
@extends('frontend.common.template', [
    'cabecalhoTexto'  => 'Blog',
    'cabecalhoImagem' => asset('assets/img/blog/'.$blogCabecalho->cabecalho)
])

@section('content')

    <div class="blog">
        <div class="center">
            <div class="right">
                <div class="blog-thumbs">
                    @include('frontend.blog.thumbs', ['posts' => $postsThumbs])
                </div>
                @unless($postsThumbs->currentPage() >= $postsThumbs->lastPage())
                <a href="#" id="blog-carregar-mais" data-url="{{ route('blog', $categoria->slug) }}">
                    CARREGAR MAIS &raquo;
                </a>
                @endunless
            </div>
            <div class="left">
                <div class="categorias">
                    <h4>CATEGORIAS</h4>

                    <a href="{{ route('blog') }}" @if($categoria->slug == null) class="active" @endif>Todas</a>
                    @foreach($categorias as $c)
                    <a href="{{ route('blog', $c->slug) }}" @if($categoria->slug == $c->slug) class="active" @endif>{{ $c->titulo }}</a>
                    @endforeach
                </div>

                @if(!count($postsList))
                <div class="nenhuma">Nenhum post encontrado.</div>
                @endif

                <div class="links" id="posts-links" data-pagina="{{ $postsList->currentPage() }}" data-url="{{ route('blog', $categoria->slug) }}">
                    @foreach($postsList as $post)
                    <a href="{{ route('blog.show', [$post->categoria->slug, $post->slug]) }}">
                        &raquo; {{ $post->titulo }} <span>{{ $post->data }}</span>
                    </a>
                    @endforeach
                </div>

                <div class="controls" id="posts-controls">
                    <a href="#" id="posts-anteriores" @if($postsList->currentPage() >= $postsList->lastPage()) class="disabled" @endif>&laquo; Anteriores</a>
                    <a href="#" id="posts-proximas" @if($postsList->currentPage() == 1 || $postsList->lastPage() < $postsList->currentPage()) class="disabled" @endif>Próximas &raquo;</a>
                </div>
            </div>
        </div>
    </div>

@endsection

laravel/resources/views/frontend/blog/show.blade.php
@extends('frontend.common.template', [
    'cabecalhoTexto'  => 'Blog',
    'cabecalhoImagem' => asset('assets/img/blog/'.$blogCabecalho->cabecalho)
])

@section('content')

    <div class="blog">
        <div class="center">
            <div class="right">
                <div class="blog-thumb">
                    <img src="{{ asset('assets/img/blog/capas/'.$post->capa) }}" alt="">
                    <div class="textos">
                        <h1>{{ $post->titulo }}</h1>
                        <div class="info">
                            {{ Tools::formataData($post->data) }} <span></span> {{ mb_strtoupper($post->categoria->titulo) }}
                        </div>
                        <div class="texto">
                            {!! $post->texto !!}
                        </div>
                    </div>
                </div>
                <div class="blog-comentarios">
                    @if(count($post->comentariosAprovados))
                    <h5>COMENTÁRIOS</h5>
                    @foreach($post->comentariosAprovados as $comentario)
                    <div class="comentario">
                        <p>{{ $comentario->comentario }}</p>
                        <span class="dados">{{ $comentario->nome }} &middot; {{ Tools::formataData($comentario->created_at) }}</span>
                    </div>
                    @endforeach
                    @endif

                    <form action="" id="form-comentario">
                        <h5>COMENTE</h5>
                        <input type="hidden" name="post" id="post" value="{{ $post->id }}">
                        <input type="text" name="nome" id="nome" placeholder="nome" required>
                        <input type="email" name="email" id="email" placeholder="e-mail" required>
                        <textarea name="comentario" id="comentario" placeholder="comentário" required></textarea>
                        <input type="submit" value="ENVIAR &raquo;">
                        <div id="form-comentario-response"></div>
                    </form>
                </div>
            </div>
            <div class="left">
                <div class="categorias">
                    <h4>CATEGORIAS</h4>

                    <a href="{{ route('blog') }}" @if($post->categoria->slug == null) class="active" @endif>Todas</a>
                    @foreach($categorias as $c)
                    <a href="{{ route('blog', $c->slug) }}" @if($post->categoria->slug == $c->slug) class="active" @endif>{{ $c->titulo }}</a>
                    @endforeach
                </div>

                @if(!count($postsList))
                <div class="nenhuma">Nenhum post encontrado.</div>
                @endif

                <div class="links" id="posts-links" data-pagina="{{ $postsList->currentPage() }}" data-url="{{ route('blog', $post->categoria->slug) }}">
                    @foreach($postsList as $post)
                    <a href="{{ route('blog.show', [$post->categoria->slug, $post->slug]) }}">
                        &raquo; {{ $post->titulo }} <span>{{ $post->data }}</span>
                    </a>
                    @endforeach
                </div>

                <div class="controls" id="posts-controls">
                    <a href="#" id="posts-anteriores" @if($postsList->currentPage() >= $postsList->lastPage()) class="disabled" @endif>&laquo; Anteriores</a>
                    <a href="#" id="posts-proximas" @if($postsList->currentPage() == 1 || $postsList->lastPage() < $postsList->currentPage()) class="disabled" @endif>Próximas &raquo;</a>
                </div>
            </div>
        </div>
    </div>

@endsection

laravel/resources/views/frontend/blog/thumbs.blade.php
@foreach($posts as $post)
<div class="blog-thumb">
    <img src="{{ asset('assets/img/blog/capas/'.$post->capa) }}" alt="">
    <div class="textos">
        <h1>{{ $post->titulo }}</h1>
        <div class="info">
            {{ Tools::formataData($post->data) }} <span></span> {{ mb_strtoupper($post->categoria->titulo) }}
        </div>
        <p>{!! $post->chamada !!}</p>
        <a href="{{ route('blog.show', [$post->categoria->slug, $post->slug]) }}">LER MAIS &raquo;
        </a>
    </div>
</div>
@endforeach